### ISSUE TITLE
PCAP transcript view should show src/dest IP and src/dest port

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/securityonion#1060]
I typically view PCAPs as a transcript by disabling both `Show all packet data` and `HEX`. But when I do that, I can no longer see the IP address and port information. 

![Screen Shot 2020-07-23 at 7 30 14 AM](https://user-images.githubusercontent.com/1659467/88281889-75c23f00-ccb6-11ea-8426-8f1a7dc6ee6d.png)

It would be nice to have a single summary line in that view that shows IP address and port information. For example, see the aqua colored summary section in CapMe:
![capme](https://user-images.githubusercontent.com/1659467/88281040-f97b2c00-ccb4-11ea-854e-02cf8035c5e4.png)

**Comment by jertel** [comment]
This information is available in the job details expansion panel.

![image](https://user-images.githubusercontent.com/16639611/88324819-3d405680-ccf2-11ea-9129-f3443875d880.png)

I can move those 4 pieces up to the collapsed panel line so that they're always visible, next to the job ID and sensor name. I had kept them off to avoid horizontal scrolling on mobile but from past discussions since then I'm not sure that mobile is a widely used view.

**Comment by dougburks** [comment]
Yeah, IP address and port information is more important than mobile compatibility.
