### ISSUE TITLE
FEATURE: SOC Grid Members should prompt for confirmation before actually deleting

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/securityonion#11223]
We should consider prompting for confirmation when a user clicks the DELETE button in SOC Grid Members.

![image](https://github.com/Security-Onion-Solutions/securityonion/assets/1659467/6355b24a-81b5-4d92-94f5-e852015cd875)

**Comment by jertel** [comment]
This was considered at the time of initial development. Since the salt state on the minion will re-add the minion key to the manager, it will show up again on its own. That was the reasoning for avoiding additional popups. 

As multiple people have expressed that they prefer to see a popup, the prompt will be added in a future release.

**Comment by jertel** [comment]
Verified:


![Image](https://github.com/Security-Onion-Solutions/securityonion/assets/16639611/c7bda353-4ad4-4542-a16f-da4718999090)
