### ISSUE TITLE
secrets not complete

### ISSUE THREAD

**Issue by danielo37** [Security-Onion-Solutions/securityonion#11682]
Hello team,

I installed Security Onion as in the documentation and official videos but at the end I got a problem which is: I am not able to authenticate to playbook with anonymous authentication, after a quick research I found that I miss a key in my secrets playbook_automation_api_key when I type sudo salt-call pillar.get secrets I get the following:
"""
local:
    ----------
    import_pass:
        h6yYnaNk8ZEtgoWfs9MT
    influx_pass:
        R0Rfomj7FoVQ83Z9Xpy3
    mysql:
        V9UymEqolgjr0iByNNWQ
    playbook_admin:
        CnD2jWWkIpFTn3K106zx
    playbook_automation:
        Es7iMTHiVYd7aoo7T3JU
    playbook_automation_api_key:
        None
    playbook_db:
        EgR6LirmWOu4ns9OLPQ5
"""
is there a way to create that without reintalling the instance "it is a standalone deployment"

Thank you for your answers.

**Comment by dougburks** [comment]
Instead of creating an ISSUE, please start a new DISCUSSION at https://github.com/Security-Onion-Solutions/securityonion/discussions. If you're using version 2.4, please start that new discussion in the 2.4 category at https://github.com/Security-Onion-Solutions/securityonion/discussions/categories/2-4.
