### ISSUE TITLE
logstash-filter-tld

### ISSUE THREAD

**Issue by bergsjoh** [Security-Onion-Solutions/securityonion#12065]
SO 2.4.30 (logstash 8.10.4) introduced a bug in logstash-filter-tld described here: https://github.com/logstash-plugins/logstash-filter-tld/issues/25

Fixed by upgrading logstash-filter-tld plugin from 3.1.2 to 3.1.3.

**Comment by dougburks** [comment]
> SO 2.4.30 (logstash 8.10.4) introduced a bug in logstash-filter-tld described here: https://github.com/logstash-plugins/logstash-filter-tld/issues/25

We will be upgrading the Elastic stack in the future which would most likely include a newer logstash-filter-tld plugin.

I don't believe we use logstash-filter-tld by default and typically recommend that if users are modifying pipelines that they do so via Elasticsearch ingest rather than via Logstash:
https://docs.securityonion.net/en/2.4/logstash.html#parsing
https://docs.securityonion.net/en/2.4/elasticsearch.html#parsing

It looks like there is an Elasticsearch ingest processor that provides similar functionality to the logstash-filter-tld plugin:
https://www.elastic.co/guide/en/elasticsearch/reference/current/registered-domain-processor.html

> Fixed by upgrading logstash-filter-tld plugin from 3.1.2 to 3.1.3.

It seems like you've already fixed your issue and I don't think others are likely to run into this, so I don't think there's anything else for us to do here other than close the issue.

If you have further questions or problems, please start a new discussion at https://securityonion.net/discuss.
