### ISSUE TITLE
2.4 install not properly detecting "cloud" environment

### ISSUE THREAD

**Issue by ebdavison** [Security-Onion-Solutions/securityonion#12891]
If you are very familiar with the latest version of the product and are confident you have found a bug in Security Onion, you can continue with creating an issue here, but please make sure you have done the following:
- duplicated the issue on a fresh installation of the latest version
- provide information about your system and how you installed Security Onion
- include relevant log files
- include reproduction steps

I am attempting to install version 2.4 from git on a ubuntu 22.0.4 server.  This server is on a hosted VPS (contabo) and is not properly being detected as a cloud environment so fails after bond0 is created with an error about activating the interface (interface name mismatch).

Looks like setup/so-functions checks for "Amazon", "amazon" and "Google" to determine if the server is "in the cloud".  Contabo uses qemu so the bios-vendor presents as "SeaBIOS".  This should so be detected as it is no a hardware platform.

```
root@hostname:/root# dmidecode -s bios-vendor
SeaBIOS
```

**Comment by dougburks** [comment]
> I am attempting to install version 2.4 from git on a ubuntu 22.0.4 server.

This is not officially supported:
https://docs.securityonion.net/en/2.4/network-installation.html

> This server is on a hosted VPS (contabo) and is not properly being detected as a cloud environment so fails after bond0 is created with an error about activating the interface (interface name mismatch).

Per your other issue at https://github.com/Security-Onion-Solutions/securityonion/issues/12892, you may be able to avoid the bond0 sniffing interface by choosing MANAGER or MANAGERSEARCH:
https://docs.securityonion.net/en/2.4/architecture.html#management
https://docs.securityonion.net/en/2.4/architecture.html#manager-search

If you have further questions or problems, please start a new DISCUSSION at https://securityonion.com/discuss rather than creating an ISSUE here.
