### ISSUE TITLE
2.4 standalone in a "cloud" environment requires a second NIC

### ISSUE THREAD

**Issue by ebdavison** [Security-Onion-Solutions/securityonion#12892]
If you are very familiar with the latest version of the product and are confident you have found a bug in Security Onion, you can continue with creating an issue here, but please make sure you have done the following:
- duplicated the issue on a fresh installation of the latest version
- provide information about your system and how you installed Security Onion
- include relevant log files
- include reproduction steps

I am attempting to install on a VPS hosted by contabo.  This is actually a qemu setup and only 1 NIC is provided.  

As a standalone install, with no physical hardware to sniff, the installer should allow the installation to complete without a sniffing interface.  2.3 used to allow this and now, when trying to install a 2.4 replacement, the installer cannot continue without this second NIC.

**Comment by dougburks** [comment]
> As a standalone install, with no physical hardware to sniff, the installer should allow the installation to complete without a sniffing interface. 2.3 used to allow this and now, when trying to install a 2.4 replacement, the installer cannot continue without this second NIC.

If you don't have a sniffing interface, then you shouldn't choose the STANDALONE option. You should be able to choose the MANAGER or MANAGERSEARCH option and they should work correctly with only 1 NIC. 

For more information, please see:
https://docs.securityonion.net/en/2.4/architecture.html#standalone
https://docs.securityonion.net/en/2.4/architecture.html#management
https://docs.securityonion.net/en/2.4/architecture.html#manager-search

If you have further questions or problems, please start a new DISCUSSION at https://securityonion.com/discuss rather than creating an ISSUE here.
