### ISSUE TITLE
Document how admins can access Cortex, if it's not already covered in 2.x docs

### ISSUE THREAD

**Issue by jertel** [Security-Onion-Solutions/securityonion#1301]

**Comment by dougburks** [comment]
Here's the current Cortex doc:
https://docs.securityonion.net/en/2.1/cortex.html

It's under the SOC section since SOC currently has a link to Cortex.  If that link is going away, we can move the page to a different section and update it to include the URL for admins to access it.

Let me know of any other changes that need to be made and I'll take care of them.

**Comment by dougburks** [comment]
I've moved Cortex from the `SOC` section to the `Customizing for Your Environment` section and added the following text:
```
Log into the Cortex web interface at /cortex (at the IP address or hostname of your Security Onion installation).
```

Updated page is at https://docs.securityonion.net/en/2.2/cortex.html.  Let me know if any other changes need to be made.
