### ISSUE TITLE
Error preventing login on chrome: A request failed due to a missing or invalid csrf_token value.

### ISSUE THREAD

**Issue by BustedSec** [Security-Onion-Solutions/securityonion#1345]
I get the error message "A request failed due to a missing or invalid csrf_token value." in a big red bar at the top of the page when trying to login while using chrome. This error does not happen on firefox. I am attempting to access the interface  via the hostname over https which is how it was configured during setup. screen shot attached 
![image](https://user-images.githubusercontent.com/7432967/93164452-7f30bc00-f6e7-11ea-9ad7-7dceac4ef28f.png)

**Comment by dougburks** [comment]
Please try a fresh installation of 2.2 (released yesterday):
https://docs.securityonion.net/en/2.2/community-support.html

If you have further questions or problems, please use the community support forum (instead of this issue tracker):
https://docs.securityonion.net/en/2.2/community-support.html

Thanks!
