### ISSUE TITLE
what's the different between Security Onion 16.04 and Security Onion 2.0 (Pre-release) 

### ISSUE THREAD

**Issue by MarkHappyShao** [Security-Onion-Solutions/securityonion#1370]
I just want to know what's the different between Security Onion 16.04 and Security Onion 2.0 (Pre-release) ??? can somebody answer me? thank you so much

**Comment by dougburks** [comment]
From https://docs.securityonion.net/en/2.2/about.html:
![image](https://user-images.githubusercontent.com/1659467/93662623-7b769f80-fa2f-11ea-904b-3105a3bb018c.png)


If you have further questions or problems, please post in the community support forum (rather than this issue tracker):
https://docs.securityonion.net/en/2.2/community-support.html

Thanks!
