### ISSUE TITLE
SOC Alerts - Improvements for "Group By Sensor, Source IP/Port, Destination IP/Port, Name" query

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/securityonion#1373]
These suggested workflows were from before we had the `Drilldown into this value` quick action, so they are no longer as important, but still might be nice to have if they can be implemented easily.

**As an analyst, I want to pivot from the alert to full packet capture so that I see the entire stream.**

_If I select the "Group By Sensor, Source IP/Port, Destination IP/Port, Name" query, then each row is an individual stream and the Quick Bar could include the PCAP option._

**As an analyst, I want to pivot to all logs relating to that alert so that I can see the context around the alert.**

_If I select the "Group By Sensor, Source IP/Port, Destination IP/Port, Name" query, then each row is an individual stream and the Quick Bar could allow me to pivot to Hunt based on the Community ID in one of those alerts._

For these changes, the pivots might need to grab the network tuple information or expose `network.community_id` and use that.

**Comment by jertel** [comment]
Group records will now enable the PCAP quick action if the network.community_id field is present.

Since the default Alerts query for Network Alerts already includes network.community_id field both the requests in the description are now implemented, since for the second request the user can already click on the community_id field and choose the Hunt quick action.
