### ISSUE TITLE
Suricata doesn't work

### ISSUE THREAD

**Issue by einsidhe** [Security-Onion-Solutions/securityonion#13942]
Good day.

Problem:
Suricata doesn't work,
No traffic is captured. 

Hardware: 
Physical server with 2 NICs, first for monitoring, second for capture (mirrored port)

What was done:
1. sudo soup
2. so-suricata-restart --force
3. curl testmynids.org/uid/index.html
4. Suricata -> full upgrade 
4. Multiple physical server reboots
5. Multiple rules recretion and edition

Please fix.

**Comment by dougburks** [comment]
Please go through the troubleshooting steps at https://docs.securityonion.net/en/2.4/suricata.html#troubleshooting-alerts.

If you have continue to have problems, please start a new discussion at https://securityonion.net/discuss (rather than creating an issue here) and provide the output of each of the troubleshooting steps above.
