### ISSUE TITLE
Security Onion 2.2.0.rc3: Default winlogbeat MSI package for Windows is missing configuration file

### ISSUE THREAD

**Issue by faisalusuf** [Security-Onion-Solutions/securityonion#1478]
After downloading the MSI package from SOC interface, the winlogbeat.yml found missing.

`Exiting: error loading config file: open C:\ProgramData\Elastic\Beats\winlogbeat\winlogbeat.yml: The system cannot find the file specified.`

**Comment by dougburks** [comment]
Please try copying `C:\ProgramData\Elastic\Beats\winlogbeat\winlogbeat.example.yml` to `C:\ProgramData\Elastic\Beats\winlogbeat\winlogbeat.yml` and making changes as necessary:
https://docs.securityonion.net/en/2.2/beats.html#winlogbeat

If you have further questions or problems, please use the support forum (instead of this issue tracker):
https://docs.securityonion.net/en/2.2/community-support.html

Thanks!
