### ISSUE TITLE
Changing config of logstash docker

### ISSUE THREAD

**Issue by epifanoviv** [Security-Onion-Solutions/securityonion#1503]
Good day! 

I change config file /opt/so/conf/logstash/pipelines/manager/* and see the same config file in so-logstash docker. But changes have not been applied. After restarting docker container configs returned to default. 

Please tell me how can i change config in so-logstash docker and apply settings.

**Comment by dougburks** [comment]
Please see:
https://docs.securityonion.net/en/2.2/logstash.html#adding-new-logs-or-modifying-existing-parsing

If you have further questions or problems, please use the community support forum (instead of this issue tracker):
https://docs.securityonion.net/en/2.2/community-support.html#forum

Thanks!
