### ISSUE TITLE
[Curator Default Config]: Add Hint to Docs for Housekeeping Jobs

### ISSUE THREAD

**Issue by gebhard73** [Security-Onion-Solutions/securityonion#1509]
Hi,

the default configuration of curator AFAIK e.g. for single node / testing scenario is to close data files older than 30 days and delete data files when 90% of the disk capacity is reached.

Depending on the concrete situation this doesn't work because the size of closed data files can't be determined by curator and then the closed files won't be considered during calculation of total size. 

**Example:**

- disk: 100 GB, limit 90 GB
- current date: 2020-10-13
- data-2020-09-01, 10 GB, closed
- data-2020-09-02, 10 GB, closed
- data-2020-09-03, 50 GB, closed
- [no data in between for the sake of a simple example]
- data-2020-10-12, 15 GB, open
- data-2020-10-13, 6 GB, open, filling up

-> space calculation in curator can only sum up the open files, i.e. 21 GB, so the actionable list for deletion is empty
-> this leads to elasticsearch reaching the hard limit and stopping accepting new data

I'd suggest adding a hint to the documentation for this case here: https://docs.securityonion.net/en/latest/curator.html

Example:
`Warning: Depending on your concrete set-up you are strongly advised to customize the housekeeping jobs of curator to suit your needs. The default jobs to close index files after 30 days and start deleting files if capacity reaches 90% don't work for every situation, esp. in single host (testing) scenarios. Deletion of files by curator based on space is considered having caveats, see https://www.elastic.co/guide/en/elasticsearch/client/curator/current/filtertype_space.html . It may help to delete index files by age instead of space and / or leave index files open for a longer time periode (which may have other disadvantages).
`

Perhaps we should add an example also to the documentation?

Thanks!

**Comment by dougburks** [comment]
Hi @gebhard73 ,

We do have a cronjob that runs `/usr/sbin/so-curator-closed-delete` (which in turn calls `/usr/sbin/so-curator-closed-delete-delete` which is supposed to manually delete any closed indices left behind by curator. However, it looks like Elasticsearch has changed the way they display closed indices so that script is no longer working properly. I've just updated `so-curator-closed-delete-delete` to handle the new output:
https://github.com/Security-Onion-Solutions/securityonion/commit/ad50b5d6403f8c53e4b450502945bd921666a32b#diff-9f90044f32ca0152c18146ecf3c7edb45b803f48cae9738a231946b704cce794

Could you try the new version and see if it works for you?
https://raw.githubusercontent.com/Security-Onion-Solutions/securityonion/dev/salt/curator/files/bin/so-curator-closed-delete-delete

You should be able to place that file at `/opt/so/saltstack/default/salt/curator/files/bin/so-curator-closed-delete-delete` (on your manager if you have a distributed deployment) and then run `sudo salt-call state.highstate` to update.

Please let us know how it goes.

Thanks!

**Comment by gebhard73** [comment]
Many thanks, I'll have a look (may take some time) and will let you know.

**Comment by dougburks** [comment]
I just made a change which may be incompatible with your RC3 installation, so please use this RC3 version for your testing:
https://github.com/Security-Onion-Solutions/securityonion/blob/ad50b5d6403f8c53e4b450502945bd921666a32b/salt/curator/files/bin/so-curator-closed-delete-delete

**Comment by gebhard73** [comment]
Tnx. Actually the issue happened on a 16.04 installation ... do you have also a compatible version for that? Sorry for omitting the version - I thought it was just the docs so it doesn't seem important :-) (I haven't been able to install RC3 on my test box because of the other issues ... the testing would be done on a somewhat productive box)

**Comment by dougburks** [comment]
The script in 16.04 should work correctly since that's an older version of Elasticsearch. If you have further questions or problems relating to 16.04, then please use the 16.04 mailing list (instead of this 2.x issue tracker):
https://docs.securityonion.net/en/16.04/mailing-lists.html

Thanks!
