### ISSUE TITLE
Enable users to have more control over Grafana

### ISSUE THREAD

**Issue by m0duspwnens** [Security-Onion-Solutions/securityonion#1633]
On another note - I wish we had more control over Grafana.  Like being able to put all the dashboards on the home screen and not have them wiped out each time I visit the site.  Or being able to enable automatic refresh, or synchronized markers across all the charts.

_Originally posted by @B3DTech in https://github.com/Security-Onion-Solutions/securityonion/discussions/1600#discussioncomment-110114_

**Comment by m0duspwnens** [comment]
@B3DTech
This is could be from Salt resetting your changes when the highstate runs every 15 minutes. Can you help me understand what you are trying to do when you mention putting all the dashboards on the home screen?

Bonus points for screen shots.

Thanks.

**Comment by m0duspwnens** [comment]
related to: https://github.com/Security-Onion-Solutions/securityonion/issues/1632

**Comment by B3DTech** [comment]
Ever since I started using 2.x, whenever I went to Grafana, it takes you immediately to the manager node dashboard, which is fine.  But if I wanted to view any other dashboards, I have to go the menu, Manage, Expand the node menu, then click the node.  Each and every time I want to change to a different dashboard.

What would be nice is adding a links option to each dashboard to be able to quickly navigate between them, as I have in this screenshot:

![image](https://user-images.githubusercontent.com/32655512/97043429-77fb9a00-1540-11eb-8ede-075a73c21a39.png)

If you want multiple links menus, you can add tags to the dashboard (manager, search, sensor), then create links menus for each node type and use the tag to automatically create links to them.

**Comment by dougburks** [comment]
> Ever since I started using 2.x, whenever I went to Grafana, it takes you immediately to the manager node dashboard, which is fine. But if I wanted to view any other dashboards, I have to go the menu, Manage, Expand the node menu, then click the node. Each and every time I want to change to a different dashboard.

You may have to do this the first time you access Grafana on a new installation, but once you've accessed the node dashboards, they should be added to `Recently viewed dashboards` which is accessible by simply clicking the Dashboards icon:
![Screen Shot 2020-10-24 at 8 04 16 AM](https://user-images.githubusercontent.com/1659467/97081308-9361b600-15cf-11eb-890d-585efb58e6aa.png)
