### ISSUE TITLE
Hunt groupby sometimes requires manually adding .keyword

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/securityonion#2001]
Hunt normally tries to determine if it needs to add `.keyword` when performing a groupby. However, sometimes this doesn't work and we have to manually add `.keyword` to get the groupby to work.

Here is one example:
https://github.com/Security-Onion-Solutions/securityonion/discussions/1993

Other examples can be seen in the default Hunt queries:
https://github.com/Security-Onion-Solutions/securityonion/blob/master/salt/soc/files/soc/hunt.queries.json

**Comment by jertel** [comment]
This is due to overlapping field names across multiple Kibana index patterns. SOC will now be more selective about which index patterns it will try to match field names. In this case it was the *:logstash-beats* index pattern that had a similarly named field that happened to be aggregated, conflicting with the *:so-* field which was not aggregated.
