### ISSUE TITLE
FEATURE: Redirect to login when session expires

### ISSUE THREAD

**Issue by weslambert** [Security-Onion-Solutions/securityonion#3222]
When a session expires return to the logon page instead of showing the red banner at the top with error messages.

I know that it is easily fixed with a simple refresh of the page, and I am back at the logon screen. But it would be nice if the application would not show stale data with an error at the top of the page. 

Joe

_Originally posted by @joeb1kenobe in https://github.com/Security-Onion-Solutions/securityonion/discussions/3185_

**Comment by jertel** [comment]
Implemented in 2.3.50. 

When the SOC browser app attempts a server side call and that call fails due to an invalid session then the SOC interface will be redirected to the login prompt, instead of showing an error while appearing to be still logged in. 

Additionally, browsers logged into SOC but idle (no autorefresh hunt/alerts, no user interaction) will eventually detect their login session is invalid and redirect to the login screen automatically.
