### ISSUE TITLE
so-scripts: Group services for start/stop/restart

### ISSUE THREAD

**Issue by weslambert** [Security-Onion-Solutions/securityonion#383]
We need a way to group start/stop/restart of services based on functions, similar to:

`sudo so-nids-start/stop/restart`
`sudo so-sensor-start/stop/restart`
`sudo so-elastic-start/stop/restart`

**Comment by petiepooo** [comment]
Can we also make it so that salt doesn't automatically restart whatever processes were stopped on the next highstate, at least until the next reboot or manual (re)start of them?

I see tons of questions on the forums about "how do I stop such-and-such?"  The response is generally, "do you mean to permanently disable it?"  No; I just want to stop it for a while while I perform some other action.  You know, like when I ran 'so-nids-stop on 16.04 and it stayed stopped until I started it again (or updated rules or rebooted).
