### ISSUE TITLE
FEATURE: Allow for Kibana customizations via pillar

### ISSUE THREAD

**Issue by defensivedepth** [Security-Onion-Solutions/securityonion#3933]
Kibana sample size is reset to `100` every highstate. This setting should be configurable

**Comment by nopoxan578** [comment]
Please correct me if I'm wrong, this is the case for all kibana settings that are supposed to be configurable.
Also fields formatting..

**Comment by gebhard73** [comment]
Can you pls make this a high prio fix? It is really annoying to lose all custom Kibana settings ... Time settings, date format settings, sample sizese, ... Tnx.

**Comment by defensivedepth** [comment]
It would be helpful if you could list out what specific settings you are trying to customize, thanks!

**Comment by gebhard73** [comment]
Thanks for getting back to me - certainly:

- sampleSize
- dateFormat:dow
- format:number:defaultLocale
- theme:version
- timepicker:quickRanges
- timepicker:timeDefaults
- discover:sampleSize
- dashboard:defaultDarkTheme
- theme:darkMode
- defaultRoute

... and others to come :-)

It would be nice to have it saved on a per-user basis (even because of dark mode is very user-dependent...) - but I understand this would not work because SO is using one anonymous user for all real users. But it should be easily configurable - and not being able to even set the parameters in `/opt/so/saltstack/local/salt/kibana/etc/config.json` is a little bit frustrating ;-) Thanks!

**Comment by m0duspwnens** [comment]
https://github.com/Security-Onion-Solutions/securityonion/issues/4969 opened to track allowing for discover:sampleSize adjustments. We will need to address the remaining configuration options in a future release.
